name = "realtime-worker"
main = "realtimeworker/index.js"
compatibility_date = "2024-09-23"
node_compat = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OrderStatusDurableObject"]

[[durable_objects.bindings]]
name = "order_status_do"
class_name = "OrderStatusDurableObject"

[vars]
REALTIME_WORKER_URL = "https://realtime-worker.shyaamdps.workers.dev"
LOG_WORKER_URL = "https://log-worker.shyaamdps.workers.dev"
INTER_WORKER_API_KEY = "ECOMSECRET"

